sudo: required
services:
  - docker

before_install:
  - docker build -t jianelectric/docker-react-cicd -f Dockerfile.dev .

script:
  - docker run jianelectric/docker-react-cicd npm run test -- --coverage